/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.90.
*        Compiled Aug 19 2004, 09:07:56
*          (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: 96hailida
* Dimensions:  96 * 96
* NumColors:   2
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colors96hailida[] = {
     0x000000,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Pal96hailida = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &Colors96hailida[0]
};

static GUI_CONST_STORAGE unsigned char ac96hailida[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ________, ______X_, __X___X_, ________, __XXXXXX, XXXXX___, __X_____, ________, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ________, ______X_, __X___X_, ________, __XXXXXX, XXXXX___, __X_____, ________, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ________, ______X_, ______X_, ________, ____X___, ____X___, __X_____, ________, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, __XXXXXX, XXX___X_, ______XX, X_______, ____X___, ____XXXX, XXX___XX, XXXXXXX_, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, __X_____, __X___X_, ________, X_______, ____X___, ________, XXX___X_, ______X_, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, __X_____, __X___X_, __XXX___, X___X___, XXXXX___, X_______, XXX___X_, ______X_, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, __X_____, __X___X_, __XXX___, X___X___, X_______, ________, __X___X_, ______X_, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, __X_____, __X___XX, XXXXXXXX, X___XXXX, X_____X_, __X_____, __X___X_, ______X_, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, __X_____, __X___XX, XXX_____, ____X___, ______X_, ________, __X___X_, ______X_, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, __X_____, __X___XX, XXX_____, ____X___, __X___XX, X___XXXX, XXX___X_, ______X_, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, __X_____, __X___X_, __X_____, ________, ______XX, X___X___, __X___X_, ______X_, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, __XXXXXX, XXX___X_, __X___X_, ______XX, X_____XX, XXXXX___, __X___XX, XXXXXXX_, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ________, ______X_, __X___X_, ______X_, ______X_, __X_____, __X_____, ________, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ________, ______X_, __X___X_, __X___X_, __X___X_, __X___X_, __X_____, ________, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ________, ______X_, __X_____, ________, __X___X_, ________, __X_____, ________, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, __X_____, ________, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXX_____, __X___X_, ________, ________, X___X___, ________, ________, XXX_____, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXX_____, __X___X_, ________, __XXX___, X___X___, XXX_____, ________, XXX_____, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, X_______, __X___X_, ________, __XXX___, ____X___, X_______, ________, XXX_____, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, X_______, XXXXXXX_, __X_____, XXXXXXX_, ____XXXX, X___X___, X_____XX, XXXXX___, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ________, X_____X_, ________, X_____X_, ____XXXX, X___X___, ________, X_______, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ______XX, X_____X_, ____XXXX, X_____X_, ____XXXX, X___XXX_, ____X___, X_______, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ________, ________, ____X___, X_____X_, ______XX, X_______, ________, X_______, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXX___, __XXX___, XXXXX___, X___XXX_, ______XX, X_______, X_____XX, X_______, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ____X___, ________, X___X___, X_______, ______XX, X_______, ______XX, X_______, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ____XXXX, X_____XX, X___XXXX, X_______, ______XX, X___X___, ____XXXX, XXXXX___, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ____X___, X_______, X_____XX, X_______, ________, X_______, ________, X___X___, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXX___, XXXXX___, XXX___XX, XXXXX___, XXX_____, XXX_____, X_______, X___XXX_, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, __XXX___, XXX_____, XXX_____, ________, ________, XXX_____, ________, X___X___, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, __XXX___, XXX___XX, XXXXX___, ________, ____XXXX, XXX___X_, ____XXXX, X___X___, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, __X_____, __X_____, ________, ________, ________, X_____X_, ____X___, X_______, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXX___X_, __XXX___, ______XX, X___XXX_, ________, X_____X_, __XXX___, XXX_____, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ________, ________, ______XX, X___XXX_, ________, X_______, ____X___, __X_____, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ____X___, X_____XX, X___XXXX, X___XXXX, XXX_____, XXX_____, ____X___, __X___X_, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ________, ________, X_______, ________, ________, XXX_____, ________, __X___X_, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ______X_, ____X___, X_______, __X_____, ________, XXX_____, __X___XX, XXXXXXX_, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ______X_, ________, ________, __X_____, ________, X_______, ______XX, XXX___X_, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, __X___X_, ________, __X_____, XXX___X_, __XXX___, X___XXX_, ______XX, XXX___XX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, __X___X_, ________, ________, __X___X_, __X_____, X___X___, ________, ________, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, __XXXXX_, __XXX___, ____X___, __X___XX, XXX___XX, X___X___, __X_____, ________, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ____XXX_, ________, ____X___, ______XX, X_____X_, ________, ________, ________, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, X___XXXX, X_____XX, X___X___, ____XXXX, X___XXX_, __X_____, X_____X_, ____X___, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, X_____X_, ______XX, X_______, ____XXX_, ________, __X_____, ______X_, ________, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, X_____X_, ____XXXX, XXX___XX, X___XXX_, __X_____, __XXXXX_, __XXXXXX, X_____X_, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, X_____X_, ______X_, __X_____, X_______, __X_____, __X___X_, __XXX___, ________, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, X___XXX_, ______X_, __X_____, X_______, __X___XX, XXX___XX, XXXXX___, ____X___, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, X_______, ______X_, __X_____, X_______, ______XX, X_____X_, __XXX___, ________, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, X_______, __XXXXXX, XXX___XX, X_____XX, X_____XX, X_____X_, __XXXXX_, __X_____, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, X_______, __X_____, ______X_, ______XX, X_______, X_____X_, ________, __X_____, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, X_______, __X_____, ____XXX_, __XXXXXX, XXX_____, XXX___X_, ________, __XXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, X_______, __X_____, ____XXX_, __XXXXXX, X_______, __X___X_, ________, ____X___, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ____XXX_, __XXXXXX, X_______, __XXXXX_, __XXXXX_, ____X___, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ________, ______X_, ________, __XXXXXX, X_______, __X_____, __X___X_, ________, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ________, ______XX, X_______, __XXXXXX, XXX___X_, __X_____, __X___X_, __X_____, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ________, ______XX, X_______, ____XXXX, X_______, __X_____, __X___X_, ________, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, __XXXXXX, XXX___XX, X_______, ____XXXX, X_______, XXXXXXX_, __XXXXX_, ________, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, __X_____, __X___X_, ________, ______X_, ________, X_____X_, ________, ________, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, __X_____, __X___X_, ______XX, X_____X_, ____X___, X_____X_, ________, __XXX___, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, __X_____, __X___X_, ________, ______X_, ____X___, ________, ________, ____X___, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, __X_____, __X___X_, ________, ____XXXX, XXXXXXX_, __XXX___, __XXXXX_, ____X___, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, __X_____, __X___X_, ________, ____XXXX, X___X___, __XXX___, ______X_, ____X___, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, __X_____, __X___X_, ____X___, X___XXXX, X___X___, XXXXXXX_, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, __X_____, __X___X_, ____X___, X_______, X___X___, __X_____, ________, X___XXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, __XXXXXX, XXX___XX, X___X___, XXX_____, X___XXX_, __X_____, X___X___, X___XXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ________, ______XX, X_______, __X_____, X_____X_, ________, ____X___, X_______, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ________, ______XX, X_____X_, __X_____, X_____XX, X___X___, ____XXXX, XXX_____, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX
};

GUI_CONST_STORAGE GUI_BITMAP bm96hailida = {
  96, /* XSize */
  96, /* YSize */
  12, /* BytesPerLine */
  1, /* BitsPerPixel */
  ac96hailida,  /* Pointer to picture data (indices) */
  &Pal96hailida  /* Pointer to palette */
};

/* *** End of file *** */
