#ifndef _ALLFONT_H_
#define _ALLFONT_H_

extern GUI_CONST_STORAGE GUI_FONT GUI_FontHZAIM_24;
extern GUI_CONST_STORAGE GUI_FONT GUI_FontHZHT_60;
extern GUI_CONST_STORAGE GUI_FONT GUI_FontHZHT_40;
extern GUI_CONST_STORAGE GUI_FONT GUI_FontHZHT_32;
extern GUI_CONST_STORAGE GUI_FONT GUI_FontHZHT_24;
extern GUI_CONST_STORAGE GUI_FONT GUI_FontHZHT_18;
extern GUI_CONST_STORAGE GUI_FONT GUI_FontHZHT_12;

#endif
